spring:
  application:
    name: CashStorage
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:https://auth.storksoft.by/auth/realms/cash-app}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cash_app}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: ${SHOW_SQL:true}
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    table: flyway_schema_history
    default-schema: public
    create-schemas: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cashstorage:
  keycloak:
    admin:
      server-url: ${KEYCLOAK_ADMIN_URL:https://auth.storksoft.by/auth}
      realm: ${KEYCLOAK_ADMIN_REALM:master}
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
      target-realm: ${KEYCLOAK_TARGET_REALM:cash-app}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

logging:
  level:
    org.springframework.security: TRACE