            - name: Mirroring Repository
  # You may pin to the exact commit or the version.
  # uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75
  uses: pixta-dev/repository-mirroring-action@v1.1.1
  with:
    # SSH private key for ssh connection to the target repository
    ssh_private_key: # optional
    # Target url
    target_repo_url: 
    # Username for ssh connection
    ssh_username: # optional, default is git
          
